/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lead {
  'hotelName' : string,
  'city' : string,
  'name' : string,
  'createdAt' : Time,
  'numberOfRooms' : bigint,
  'email' : string,
  'phoneNumber' : string,
}
export type LeadId = bigint;
export type Time = bigint;
export interface _SERVICE {
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getLead' : ActorMethod<[LeadId], Lead>,
  'getLeadsByCreatedAt' : ActorMethod<[], Array<Lead>>,
  'getLeadsByName' : ActorMethod<[], Array<Lead>>,
  'submitLead' : ActorMethod<
    [string, string, string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];