/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Lead = IDL.Record({
  'hotelName' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'numberOfRooms' : IDL.Nat,
  'email' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const LeadId = IDL.Nat;

export const idlService = IDL.Service({
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLead' : IDL.Func([LeadId], [Lead], ['query']),
  'getLeadsByCreatedAt' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLeadsByName' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Lead = IDL.Record({
    'hotelName' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'numberOfRooms' : IDL.Nat,
    'email' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const LeadId = IDL.Nat;
  
  return IDL.Service({
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLead' : IDL.Func([LeadId], [Lead], ['query']),
    'getLeadsByCreatedAt' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLeadsByName' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };